exports.PREFIX = ".";
exports.TOKEN = process.env.TOKEN//process.env.TOKEN
exports.GOOGLE_API_KEY = process.env.
exports.IMGUR_API_KEY = process.env.
exports.MongoUrl = process.env.
exports.dblToken = process.env.
exports.webhookAuthPass = process.env.
exports.HEROKUPORT = process.env.PORT
exports.CatAPIKey = process.env.
exports.RconSecrets = [process.env.RconAdress, process.env.RconPass]